### ISSUE TITLE
Add NodeList type support to forEach

### ISSUE THREAD

**Issue by yoyurec** [codemix/fast.js#78]
Looking to problem described in http://toddmotto.com/ditch-the-array-foreach-call-nodelist-hack article:
```
var myNodeList = document.querySelectorAll('li'); // grabs some <li>

// Uncaught TypeError: Object #<NodeList> has no method 'forEach' 
myNodeList.forEach(function (item) {
  // :(
});
```

need to extend `fast.forEach` with NodeList

**Comment by nickb1080** [comment]
This probably requires a larger design decision. Currently, an `instanceof` check is run to decide between using array iteration methods and object iteration methods. In addition, the pull request you made will throw in an environment where `NodeList` is not defined (node, for instance). Hence the failing tests.

In general, objects that can be iterated _like_ arrays have a numeric length property. Maybe we could check like this for _arraylike_ objects (with appropriate changes for every other `instanceof` check):

```js
 module.exports = function fastForEach (subject, fn, thisContext) {
if (typeof subject.length === "number") {
     return forEachArray(subject, fn, thisContext);
   }
   else {
     return forEachObject(subject, fn, thisContext);
   }
 };
```

This would allow iteration of `NodeList`, jQuery objects, and others. (I haven't tested that this works as written, just describing a possible approach)

**Comment by phpnode** [comment]
@yoyurec as @nickb1080 says `NodeList` is undefined and therefore we can't add this. I'm wary of `length` sniffing because it will work correctly 99.999% of the time and fail spectacularly badly in rare cases. 

I think I have to close this, the solution is to just use the array version directly:
```js
var forEach = require('fast.js/array/forEach');

forEach(myNodeList, function (item) { 
  // ...
});
```

**Comment by yoyurec** [comment]
looks like **Underscore** checks `length`:
https://github.com/jashkenas/underscore/blob/master/underscore.js#L131-L146

why **fast.js** can't? Is it slow or 0.0001% fails to much?

**Comment by phpnode** [comment]
That is straight crazy:

```js
_.forEach({"some word": 1, "another word": 2, "length": 3, "yet another word": 4}, console.log.bind(console, 'lol'))
```

That very much seems like a horrible design flaw in underscore, not one I want to emulate. It's a trap.

**Comment by jdalton** [comment]
> That is straight crazy

Naw, it's a "Collection" method meaning it supports array-like objects and objects. It prioritizes array-like, those with a length, over plain objects. In this way it tackles the majority of plain object iteration as well as array-like iteration. Underscore v1.8 may be getting `_.forOwn` for object iteration which handles cases where `length` is not intended as array-like.

**Comment by nickb1080** [comment]
Requiring the correct iteration method is probably the right way to go. It's one of the benefits of the modular design of this library. Alternately, if you want all the array methods in one place you could require `fast/array`

```js
var fast = require("fast.js/array");
fast.forEach(nodeListInstance, callback);
```

**Comment by phpnode** [comment]
@jdalton thanks for the context, I suppose that's a lot more reasonable than it first seemed. It still doesn't make sense for us to do it here though.

A final way of doing this:
```js
var fast = require('fast.js');
fast.array.forEach(nodeListInstance, callback);
```

**Comment by jdalton** [comment]
> thanks for the context,

No prob, just explaining the straight crazy away :P

**Comment by yoyurec** [comment]
>A final way of doing this...

tnx! :+1: 

**PS:** is there API docs for **fast.js**?
if yes, then it would be a) good read it b) to add *Notice: 'if you want to iterate `NodeList`'... to `forEach`*

**Comment by jdalton** [comment]
If "Collection" style iteration isn't something desired for fast.js why not nix the hybrid functions in favor of just array/xyz and object/xyz?
