### ISSUE TITLE
Feature Request: Recursive flatten?

### ISSUE THREAD

**Issue by DylanPiercey** [codemix/fast.js#83]
Would be convenient.

**Comment by phpnode** [comment]
@DylanPiercey can you give some example use cases? e.g. expected input / output

**Comment by jdfm** [comment]
@DylanPiercey 

As far as I know JavaScript doesn't have a native recursive flattening method for arrays (you could flatten arrays using concat, but concat alone does not traverse arrays in arrays in arrays ... etc). So it would probably fall outside the scope of fast.js to implement that code. Plus, there are probably other libraries that take care of these kinds of features for you.

**Comment by DylanPiercey** [comment]
@phpnode your absolutely right. I think either the scope has changed since I posted this or I simply missed that this library only implements standard lib features.
