### ISSUE TITLE
Typings?

### ISSUE THREAD

**Issue by tycho01** [codemix/fast.js#88]
Would you perhaps be open to the idea of having typings using the likes of TypeScript? It may seem as to clash a bit with the `fast.js` name, but to JS end-users the results would be the same anyway. :P

**Comment by phpnode** [comment]
Hey, sorry I didn't see this, I'd definitely accept a PR.

**Comment by mflux** [comment]
+1 on this. Currently working on something with annotated JS types and fast does not give proper type hints for any of its functions.
